Fix ergodash bg image
yushakobo/build-documents pull request #13
Opened 2021-08-11 09:58 UTC by kata0510

ErgoDash親指あり組み立てページの画像の修正

2021-08-13 04:12 UTC, keyaki-namiki approved these changes

2021-08-13 10:11 UTC, keyaki-namiki requested changes
8行目の「このビルドガイドでは〜」の部分について、「親指あり」と「親指なし」が入れ替わっていますので修正をお願いします

2021-08-14 05:25 UTC, keyaki-namiki requested changes
もう一行🙏

2021-08-14 05:25 UTC, keyaki-namiki commented on ErgoDash/ErgoDash_BuildGuide.md
>  親指ありの組み立ては以下のページを参照下さい。
`親指なしの組み立ては以下のページをご参照ください`

2021-08-14 05:28 UTC, kata0510 commented on ErgoDash/ErgoDash_BuildGuide.md
>  親指ありの組み立ては以下のページを参照下さい。
すいません見逃してました:pray:

2021-08-14 05:47 UTC, keyaki-namiki approved these changes

2021-08-14 05:48 UTC, merged